[cursor]
unfocused_hollow = true

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font" }

[bell]
animation = "Ease"

[window]
opacity = 0.95
blur = true

[mouse]
hide_when_typing = true

# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme


# Colors (Ayu Dark)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'
